### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [44]:

import numpy as np
primi = np.array([n for n in range(2,10) if all(n%i !=0 for i in range(2,n))])
print(primi)
print(len(primi))
print(primi.size)
[all(a for a in primi)]

[2 3 5 7]
4
4


[True]

### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [ ]:
a = np.array([n for n in range(10)])
b = np.array(a[3:8])
c = np.array(a[::-1])

# print(c)
# print(a/c)

a1 = [n for n in range(10)]
b2= a[1:6]
c1 = a[::-1]
print(a1/c1)





[1 2 3 4 5]
[0.         0.125      0.28571429 0.5        0.8        1.25
 2.         3.5        8.                inf]


C:\Users\kasse\AppData\Local\Temp\ipykernel_23584\2882173668.py:12: RuntimeWarning: divide by zero encountered in divide
  print(a1/c1)


In [65]:
a = np.array([n for n in range(10)])
a <5
np.all(a < 5)
a[a<5]

array([0, 1, 2, 3, 4])

In [ ]:
import random
z = [random.randint(10,100) for n in range(10)]
z

SyntaxError: invalid syntax (599858360.py, line 2)

In [76]:
np.argmax(z)

np.int64(2)

In [81]:
f = np.array([1,2,np.nan,44,np.nan])

In [83]:
np.max(f)

np.float64(nan)

In [89]:
k = np.array([[1,2,3],[2,3,4]])
k.shape


(2, 3)

In [98]:
mat = np.arange(20).reshape([4,5])
mat,mat[:2,2]

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([2, 7]))